/* autogenerated by Processing revision 1286 on 2022-09-19 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class processingStructure extends PApplet {

/**
*
*程序注释
*@author
*@from
*/

int c;

//调用系统方法
 public void setup(){
  //设置画面尺寸，width = 600, height = 600;
  /* size commented out by preprocessor */;
  //打印文本
  println("hello world!");
  calculate(10, 25);
  //打印计算结果
  println("c = " + c);
}

//自定义方法：计算加和
 public void calculate(int a, int b){
  //计算a加b之和并将值赋予给变量c
  c = a + b;
}


  public void settings() { size(600, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "processingStructure" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
